name: 'mybi_dbt_core'
version: '0.1.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<1.1.0"]

profile: 'mybi_dbt_core'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:       
    - "target"
    - "dbt_packages"

quoting:
    database: True
    schema: True
    identifier: True
    
vars:
    limit_data: true
    limit_data_days: 30

    mybi_dbt_core:
        account_id_ads: null
        account_id_amocrm: null        
        account_id_bitrix24: null
        account_id_currency: null
        account_id_direct: null
        account_id_facebook: null
        account_id_ga: null
        account_id_gaw: null
        account_id_metrika: null
        account_id_mytarget: null
        account_id_vkontakte: null

        caption_ads: 'google_ads'                    
        caption_amocrm: 'amocrm'
        caption_bitrix24: 'bitrix24' 
        caption_direct: 'yandex_direct'
        caption_facebook: 'facebook' 
        caption_ga: 'google_analytics' 
        caption_gaw: 'google_adwords'                    
        caption_metrika: 'yandex_metrika'
        caption_mytarget: 'mytarget' 
        caption_vkontakte: 'vkontakte' 

models:

    mybi_dbt_core:
        +materialized: table
        +enabled: true

        staging:
            +schema: staging
            +tags: ["staging"]

            ads:
                +tags: ["ads"]     
            amocrm:
                +tags: ["amocrm"]
            bitrix24:
                +tags: ["bitrix24"]
            currency:
                +tags: ["currency"]
            direct:
                +tags: ["direct"]
            facebook:
                +tags: ["facebook"]
            ga:
                +tags: ["ga"]
            gaw:
                +tags: ["gaw"]
            general:
                +tags: ["general"]
            metrika:
                +tags: ["metrika"]
            mytarget:
                +tags: ["mytarget"]
            vkontakte:
                +tags: ["vkontakte"]