
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mybi_dbt_core'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.18.0", "<0.19.0"]

# This setting configures which "profile" dbt uses for this project.
profile: 'mybi_dbt_core'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
    database: True
    schema: True
    identifier: True
    
vars:
    mybi_dbt_core:
        mybi_database: mybi-fyiupzo
        mybi_schema: dbo
        mybi_table_metrika_custom: "л»лю YM.2P_CONVERSIONS"

        account_id_b24: "19646"
        account_id_direct: "18789"
        account_id_facebook: "18787"
        account_id_adwords: "18790, 18798"
        account_id_metrika: "18795"
        account_id_mytarget: "18799"
        
        caption_metrika: 'metrika'
        caption_direct: 'yandex'
        caption_adwords: 'google'                    
        caption_facebook: 'facebook' 

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    mybi_dbt_core:
        +materialized: view
        +enabled: true       
        staging:
            +materialized: view
            +schema: staging
            +tags: ["staging"]
            metrika:
                +tags: ["metrika"]
            direct:
                +tags: ["direct"]
            gaw:
                +tags: ["gaw"]
            facebook:
                +tags: ["facebook"]
            mytarget:
                +tags: ["mytarget"]
            bitrix24:
                +tags: ["bitrix24"]
            general:
                +tags: ["general"]
        # aux:
        #     +enabled: false 
        #     +materialized: table
        #     +schema: aux
        #     +tags: ["aux"]
        # marts:
        #     +enabled: false
        #     +materialized: table
        #     +tags: ["marts"]                    
