version: '2'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssword"
    ports:
      - "1433:1433"

  dbt:
    image: mybi/dbt:latest
    entrypoint: /bin/bash
    tty: true
    volumes:
     - .:/usr/app/mybi-dbt-core