version: 2

models:
    - name: aux_metrika
      tests:
          - not_null:
              column_name: hash_key
    - name: aux_yd_keywords_facts
      tests:
          - not_null:
              column_name: hash_key
          - unique:
              column_name: hash_key
    - name: aux_gaw_keywords_facts
      tests:
          - not_null:
              column_name: hash_key
          - unique:
              column_name: hash_key
    - name: aux_fb_ads_facts
      tests:
          - not_null:
              column_name: hash_key
          - unique:
              column_name: hash_key