version: 2

models:
    - name: stg_general_clientids
      tests:
          - not_null:
              column_name: "[Идентификатор клиента]"
    - name: stg_general_dates
      tests:
          - not_null:
              column_name: "[Идентификатор даты]"
    - name: stg_general_traffic
      tests:
          - not_null:
              column_name: "[Идентификатор источника трафика]"
    - name: stg_general_locations
      tests:
          - not_null:
              column_name: "[Идентификатор местоположения]"
    - name: stg_general_sites
      tests:
          - not_null:
              column_name: "[Идентификатор сайта]"
    - name: stg_general_accounts
      tests:
          - not_null:
              column_name: "[Идентификатор записи]"
    - name: stg_general_costs_facts
      tests:
          - not_null:
              column_name: "[Идентификатор подключенного аккаунта]"

              
              
                            
              
              
              
              