version: 2

sources:
    - name: general
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: myBI general dimensions and facts
      tags: ['general']
      tables:
        - name: clientids
          identifier: general_clientids             
        - name: dates
          identifier: general_dates                
        - name: traffic
          identifier: general_traffic               
        - name: locations
          identifier: general_locations             
        - name: sites
          identifier: general_sites                 
        - name: accounts
          identifier: general_accounts              
        - name: costs_facts
          identifier: general_costs_facts

    - name: metrika
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Yandex.Metrika
      tags: ['metrika']
      tables:   
        - name: sessions_facts
          identifier: metrika_sessions_facts
        - name: goals_facts
          identifier: metrika_goals_facts
        - name: purchases_facts
          identifier: metrika_purchases_facts
        - name: devices
          identifier: metrika_devices
        - name: goals
          identifier: metrika_goals
        - name: purchases
          identifier: metrika_purchases

    - name: direct
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Yandex.Direct
      tags: ['direct']
      tables:
        - name: campaigns
          identifier: direct_campaigns
        - name: adgroups
          identifier: direct_adgroups
        - name: ads
          identifier: direct_ads
        - name: regions
          identifier: direct_regions
        - name: sitelinks
          identifier: direct_sitelinks
        - name: ads_facts
          identifier: direct_ads_facts          

    - name: gaw
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Google Adwords
      tags: ['gaw']
      tables:
        - name: campaigns
          identifier: adwords_campaigns
        - name: location_criterions
          identifier: adwords_location_criterions
        - name: adgroups
          identifier: adwords_adgroups
        - name: ads
          identifier: adwords_ads
        - name: keywords
          identifier: adwords_keywords
        - name: ads_facts
          identifier: adwords_ads_facts
        - name: keywords_facts
          identifier: adwords_keywords_facts     

    - name: ads
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Google Ads
      tags: ['ads']
      tables:
        - name: adgroups
          identifier: ads_adgroups
        - name: adgroups_facts
          identifier: ads_adgroups_facts
        - name: ads
          identifier: ads_ads
        - name: ads_facts
          identifier: ads_ads_facts
        - name: campaigns
          identifier: ads_campaigns
        - name: campaigns_facts
          identifier: ads_campaigns_facts
        - name: keywords
          identifier: ads_keywords
        - name: keywords_facts
          identifier: ads_keywords_facts
        - name: location_criterions
          identifier: ads_location_criterions
   

    - name: facebook
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Facebook
      tags: ['facebook']
      tables:
        - name: campaigns
          identifier: facebook_campaigns
        - name: adsets
          identifier: facebook_adsets
        - name: ads
          identifier: facebook_ads
        - name: creatives
          identifier: facebook_creatives
        - name: ads_facts
          identifier: facebook_ads_facts

    - name: mytarget
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: myTarget
      tags: ['mytarget']      
      tables:
        - name: campaigns
          identifier: mytarget_campaigns          
        - name: banners
          identifier: mytarget_banners            
        - name: campaigns_facts
          identifier: mytarget_campaigns_facts    
        - name: banners_facts
          identifier: mytarget_banners_facts      

    - name: bitrix24
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Bitrix24
      tags: ['bitrix24']      
      tables:
        - name: leads_facts
          identifier: bitrix24_leads_facts           
        - name: deals_facts
          identifier: bitrix24_deals_facts           
        - name: products_facts
          identifier: bitrix24_products_facts        
        - name: users
          identifier: bitrix24_users                 
        - name: deals
          identifier: bitrix24_deals                 
        - name: contacts
          identifier: bitrix24_contacts              
        - name: companies
          identifier: bitrix24_companies             
        - name: products
          identifier: bitrix24_products              
        - name: leads
          identifier: bitrix24_leads

    - name: amocrm
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: amoCRM
      tags: ['amocrm']      
      tables:
        - name: leads_facts
          identifier: amocrm_leads_facts           
        - name: users
          identifier: amocrm_users                 
        - name: leads
          identifier: amocrm_leads      
        - name: contacts
          identifier: amocrm_contacts   
        - name: companies
          identifier: amocrm_companies  
        - name: leads_attributes
          identifier: amocrm_leads_attributes
        - name: leads_tags
          identifier: amocrm_leads_tags

    - name: ga
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Google Analytics
      tags: ['ga']      
      tables:
        - name: goals
          identifier: analytics_goals
        - name: devices
          identifier: analytics_devices
        - name: events
          identifier: analytics_events
        - name: sessions_facts
          identifier: analytics_sessions_facts
        - name: goals_facts
          identifier: analytics_goals_facts
        - name: costs_facts
          identifier: analytics_costs_facts
        - name: events_facts
          identifier: analytics_events_facts
        - name: mcf_facts
          identifier: analytics_mcf_facts

    - name: currency
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: Currency Exchange Rates (CBRF)
      tags: ['currency']      
      tables:
        - name: items
          identifier: currency_items
        - name: items_facts
          identifier: currency_items_facts

    - name: vkontakte
      database: "{{ env_var('DBT_SOURCE_DATABASE') }}"
      schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
      description: VKontakte (VK)
      tags: ['vkontakte']      
      tables:
        - name: ads
          identifier: vkontakte_ads
        - name: ads_facts
          identifier: vkontakte_ads_facts
        - name: campaigns
          identifier: vkontakte_campaigns
        - name: campaigns_facts
          identifier: vkontakte_campaigns_facts
        - name: groups
          identifier: vkontakte_groups
        - name: groups_facts
          identifier: vkontakte_groups_facts
        - name: members
          identifier: vkontakte_members
        - name: members_facts
          identifier: vkontakte_members_facts
        - name: posts
          identifier: vkontakte_posts
        - name: posts_facts
          identifier: vkontakte_posts_facts
