version: 2

sources:
    - name: general
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['general']
      tables:
        - name: clientids
          identifier: general_clientids             
        - name: dates
          identifier: general_dates                
        - name: traffic
          identifier: general_traffic               
        - name: locations
          identifier: general_locations             
        - name: sites
          identifier: general_sites                 
        - name: accounts
          identifier: general_accounts              
        - name: costs_facts
          identifier: general_costs_facts

    - name: metrika
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['metrika']
      tables:   
        - name: sessions_facts
          identifier: metrika_sessions_facts
        - name: goals_facts
          identifier: metrika_goals_facts
        - name: purchases_facts
          identifier: metrika_purchases_facts
        - name: devices
          identifier: metrika_devices
        - name: goals
          identifier: metrika_goals
        - name: purchases
          identifier: metrika_purchases

    - name: direct
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['direct']
      tables:
        - name: campaigns
          identifier: direct_campaigns
        - name: adgroups
          identifier: direct_adgroups
        - name: ads
          identifier: direct_ads
        - name: ads_facts
          identifier: direct_ads_facts          

    - name: gaw
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['gaw']
      tables:
        - name: campaigns
          identifier: adwords_campaigns
        - name: adgroups
          identifier: adwords_adgroups
        - name: ads
          identifier: adwords_ads
        - name: keywords
          identifier: adwords_keywords
        - name: ads_facts
          identifier: adwords_ads_facts
        - name: keywords_facts
          identifier: adwords_keywords_facts     

    - name: facebook
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['facebook']
      tables:
        - name: campaigns
          identifier: facebook_campaigns
        - name: adsets
          identifier: facebook_adsets
        - name: ads
          identifier: facebook_ads
        - name: creatives
          identifier: facebook_creatives
        - name: ads_facts
          identifier: facebook_ads_facts

    - name: mytarget
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['mytarget']      
      tables:
        - name: campaigns
          identifier: mytarget_campaigns          
        - name: banners
          identifier: mytarget_banners            
        - name: campaigns_facts
          identifier: mytarget_campaigns_facts    
        - name: banners_facts
          identifier: mytarget_banners_facts      

    - name: bitrix24
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['bitrix24']      
      tables:
        - name: leads_facts
          identifier: bitrix24_leads_facts           
        - name: deals_facts
          identifier: bitrix24_deals_facts           
        - name: products_facts
          identifier: bitrix24_products_facts        
        - name: users
          identifier: bitrix24_users                 
        - name: deals
          identifier: bitrix24_deals                 
        - name: contacts
          identifier: bitrix24_contacts              
        - name: companies
          identifier: bitrix24_companies             
        - name: products
          identifier: bitrix24_products              
        - name: leads
          identifier: bitrix24_leads

    - name: amocrm
      database: "{{ env_var('DBT_MSSQL_DATABASE') }}"
      schema: "{{ env_var('DBT_MSSQL_SCHEMA') }}"
      tags: ['amocrm']      
      tables:
        - name: leads_facts
          identifier: amocrm_leads_facts           
        - name: users
          identifier: amocrm_users                 
        - name: leads
          identifier: amocrm_leads      
        - name: contacts
          identifier: amocrm_contacts   
        - name: companies
          identifier: amocrm_companies  
        - name: leads_info
          identifier: amocrm_leads_attributes
        - name: leads_tags
          identifier: amocrm_leads_tags
          