name: 'mybi_dbt_core_integration_tests'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.21.0", "<0.22.0"]

profile: 'mybi_dbt_core'

source-paths: ["models"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:       
    - "target"
    - "dbt_modules"

quoting:
    database: True
    schema: True
    identifier: True
    
vars:
    limit_data: false
    limit_data_days: 365
    
    mybi_dbt_core:
        account_id_metrika: "21600"
        account_id_gaw: "18380"
        account_id_direct: "18378"
        account_id_facebook: "18441"
        account_id_mytarget: "18799"
        account_id_bitrix24: "19646"
        account_id_amocrm: "20652"   
        account_id_ga: "18783, 26557"

        caption_metrika: 'yandex_metrika'
        caption_direct: 'yandex_direct'
        caption_adwords: 'google_adwords'                    
        caption_facebook: 'facebook' 
        caption_mytarget: 'mytarget' 
        caption_bitrix24: 'bitrix24' 
        caption_amocrm: 'amocrm'
        caption_ga: 'google_analytics' 

seeds:
  +pre-hook: "SET data_type_default_nullable = 1"
  +quote_columns: true  

  mybi_dbt_core_integration_tests:
    
    general:
        +tags: ["general"]
        general_traffic:
            +column_types:
                grouping: String
                content: String
                source: String
                campaign: String
        general_sites:
            +column_types:
                domain: String
        general_accounts:
            +column_types:
                caption: String                
    amocrm:
        +tags: ["amocrm"]
    bitrix24:
        +tags: ["bitrix24"]
        bitrix24_contacts:
            +column_types:
                phone: String
        bitrix24_users:
            +column_types:
                work_phone: String
    direct:
        +tags: ["direct"]
        direct_adgroups:
            +column_types:
                adgroup_id: String
        direct_ads:
            +column_types:
                ad_id: String
    facebook:
        +tags: ["facebook"]
        facebook_ads:
            +column_types:
                ad_id: String
        facebook_adsets:
            +column_types:
                adset_id: String            
        facebook_campaigns:
            +column_types:
                campaign_id: String            
        facebook_creatives:
            +column_types:
                creative_id: String            
    gaw:
        +tags: ["gaw"]
        adwords_campaigns:
            +column_types:
                campaign_id: String
                ad_serving_optimization_status: String
        adwords_adgroups:
            +column_types:
                adgroup_id: String
        adwords_ads:
            +column_types:
                ad_id: String
                url: String
        adwords_keywords:
            +column_types:
                keyword_id: String
    metrika:
        +tags: ["metrika"]
    mytarget:
        +tags: ["mytarget"]
    ga:
        +tags: ["ga"]
