name: 'mybi_dbt_core_integration_tests'
version: '1.0.0'
config-version: 2

profile: 'mybi_dbt_core'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:       
    - "target"
    - "dbt_packages"

quoting:
    database: True
    schema: True
    identifier: True
    
vars:
    limit_data_days: 3650
    
    mybi_dbt_core:
        dbt_source_database: null
        dbt_source_schema: null

        account_id_metrika: "21600"
        account_id_gaw: "18380"
        account_id_direct: "18378"
        account_id_facebook: "18441"
        account_id_mytarget: "18799"
        account_id_bitrix24: "19646"
        account_id_amocrm: "20652"   
        account_id_ga: "18783, 26557"
        account_id_ads: "35960"

        caption_metrika: 'yandex_metrika'
        caption_direct: 'yandex_direct'
        caption_adwords: 'google_adwords'                    
        caption_facebook: 'facebook' 
        caption_mytarget: 'mytarget' 
        caption_bitrix24: 'bitrix24' 
        caption_amocrm: 'amocrm'
        caption_ga: 'google_analytics' 

seeds:
  # +quote_columns: true  

  mybi_dbt_core_integration_tests:
    
    ads:
        +tags: ["ads"]
        ads_campaigns:
            +column_types:
                campaign_id: BIGINT
        ads_adgroups:
            +column_types:
                adgroup_id: BIGINT
        ads_ads:
            +column_types:
                ad_id: BIGINT
        ads_keywords:
            +column_types:
                keyword_id: BIGINT
    general:
        +tags: ["general"]            
    amocrm:
        +tags: ["amocrm"]
    bitrix24:
        +tags: ["bitrix24"]
    direct:
        +tags: ["direct"]
        direct_adgroups:
            +column_types:
                adgroup_id: BIGINT
        direct_ads:
            +column_types:
                ad_id: BIGINT                
    facebook:
        +tags: ["facebook"]
        facebook_ads:
            +column_types:
                ad_id: BIGINT        
        facebook_adsets:
            +column_types:
                adset_id: BIGINT        
        facebook_campaigns:
            +column_types:
                campaign_id: BIGINT        
        facebook_creatives:
            +column_types:
                creative_id: BIGINT        
    gaw:
        +tags: ["gaw"]
        adwords_adgroups:
            +column_types:
                adgroup_id: BIGINT  
        adwords_ads:
            +column_types:
                ad_id: BIGINT  
        adwords_campaigns:
            +column_types:
                campaign_id: BIGINT  
        adwords_keywords:
            +column_types:
                keyword_id: BIGINT  
    metrika:
        +tags: ["metrika"]
    mytarget:
        +tags: ["mytarget"]
    ga:
        +tags: ["ga"]
