name: 'mybi_dbt_core_integration_tests'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.19.0", "<0.20.0"]

profile: 'mybi_dbt_core'

source-paths: ["models"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:       
    - "target"
    - "dbt_modules"

quoting:
    database: True
    schema: True
    identifier: True
    
vars:
    filter_days_of_data: 3
    mybi_dbt_core:
        account_id_metrika: "21600"
        account_id_adwords: "18380"
        account_id_direct: "18378"
        account_id_facebook: "18441"
        account_id_mytarget: "18799"
        account_id_b24: "19646"
        account_id_amocrm: "20652"   
        account_id_ga: "18783"

        caption_metrika: 'yandex_metrika'
        caption_direct: 'yandex_direct'
        caption_adwords: 'google_adwords'                    
        caption_facebook: 'facebook' 
        caption_mytarget: 'mytarget' 
        caption_bitrix24: 'bitrix24' 
        caption_amocrm: 'amocrm'
        caption_ga: 'google_analytics' 

seeds:
  +quote_columns: true  
  mybi_dbt_core_integration_tests:
    
    general:
        +tags: ["general"]
        general_traffic:
            +column_types:
                grouping: nvarchar(128)
                content: nvarchar(512)
                source: nvarchar(512)
                campaign: nvarchar(256)
        general_sites:
            +column_types:
                domain: nvarchar(512)
        general_accounts:
            +column_types:
                caption: nvarchar(256)                
    amocrm:
        +tags: ["amocrm"]
    bitrix24:
        +tags: ["bitrix24"]
        bitrix24_contacts:
            +column_types:
                phone: nvarchar(32)
        bitrix24_users:
            +column_types:
                work_phone: nvarchar(32)
    direct:
        +tags: ["direct"]
        direct_adgroups:
            +column_types:
                adgroup_id: nvarchar(32)
        direct_ads:
            +column_types:
                ad_id: nvarchar(32)
    facebook:
        +tags: ["facebook"]
        facebook_ads:
            +column_types:
                ad_id: nvarchar(32)
        facebook_adsets:
            +column_types:
                adset_id: nvarchar(32)            
        facebook_campaigns:
            +column_types:
                campaign_id: nvarchar(32)            
        facebook_creatives:
            +column_types:
                creative_id: nvarchar(32)            
    gaw:
        +tags: ["gaw"]
        adwords_campaigns:
            +column_types:
                campaign_id: nvarchar(32)
        adwords_adgroups:
            +column_types:
                adgroup_id: nvarchar(32)
        adwords_ads:
            +column_types:
                ad_id: nvarchar(32)
        adwords_keywords:
            +column_types:
                keyword_id: nvarchar(32)
    metrika:
        +tags: ["metrika"]
    mytarget:
        +tags: ["mytarget"]
    ga:
        +tags: ["ga"]
