name: Clickhouse Continuous Integration Tests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

jobs:
  ci_clickhouse:    

    services:
      clickhouse:
        image: yandex/clickhouse-server:21.10
        ports:
          - 9000:9000
          - 8123:8123
        env:
          DBT_SOURCE_DATABASE: default
          DBT_SOURCE_SCHEMA: default

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: wait for services to start up
        run: sleep 10
      - name: run dbt commands
        uses: kzzzr/mybi-dbt-action@mybi-dbt-core
        with:
          project_dir: ./integration_tests
        env:
          DBT_TARGET: clickhouse
          DBT_SOURCE_DATABASE: default
          DBT_SOURCE_SCHEMA: default
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
