name: PostgreSQL Continuous Integration Tests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

jobs:
  ci_postgresql:    

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          DBT_SOURCE_DATABASE: postgres
          DBT_SOURCE_SCHEMA: public

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: wait for services to start up
        run: sleep 10
      - name: run dbt commands
        uses: kzzzr/mybi-dbt-action@mybi-dbt-core
        with:
          project_dir: ./integration_tests
        env:
          DBT_TARGET: postgres
          DBT_SOURCE_DATABASE: postgres
          DBT_SOURCE_SCHEMA: public
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
