name: CI dbt on mssql

# Controls when the action will run. 
on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 5 * * *'

jobs:
  dbt_ci:    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          - ACCEPT_EULA=Y      
          - SA_PASSWORD=sa
        ports:
          - 1433:1433
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dbt mssql action
        uses: kzzzr/mybi-dbt-action@v1
        env:
          DBT_MSSQL_TARGET: ci
          DBT_MSSQL_SERVER: localhost
          DBT_MSSQL_USER: sa
          DBT_MSSQL_PASSWORD: sa
          DBT_MSSQL_DATABASE: sa
          GITHUB_PR_NUMBER: ${{ github.event.number }}
        